### ISSUE TITLE
Asynchronous command handling

### ISSUE THREAD

**Issue by jasonmitchell** [jasonmitchell/sequin#7]
Sequin needs to be able to deal with async/await code within handlers

**Comment by jasonmitchell** [comment]
I'm wondering if there's anything explicit needing to be done for this once #14 is done.  Once the command bus can be replaced it would be possible to create a bus which puts the command in a queue and then implement a post post processor which returns an Accepted status code.  Beyond this I don't think there is anything specific needing done to support asynchronous command handled.

**Comment by JoeStead** [comment]
I'm at a state where I need something like this. We can discuss how we want to tackle it tomorrow, but yeah, this pls.

**Comment by jasonmitchell** [comment]
@JoeStead are you thinking in terms of async/await stuff?  This issue was originally for asynchronous handling of commands by placing them on a queue or something (I don't think there's specific work required for this).  However I don't think it will current setup will work very well with code which needs to be awaited.

**Comment by JoeStead** [comment]
@jasonmitchell Ahh. I only had a quick glance at this before going home. Yeah, we're at the point where our Repo is now async (because of the underlying datastore and what not), but having the IHandler interface have a `void Handle` method is annoying, it would be ace if that was `Task Handle`

**Comment by jasonmitchell** [comment]
@JoeStead We will just hijack this issue because I was on the verge of closing it because there's no real work for what I originally intended this for anyway.

Right now I can think of the following options (might come up with some more while I think about):

1. Update ```IHandler``` to always return ```Task```
2. Introduce ```IAsyncHandler``` which defines a method returning ```Task```
3. Introduce an abstract base class with virtual methods for sync & async operations.  Default async implementation would wrap the sync in a ```Task```

Right now I'm leaning towards solution 1; handlers which don't await anything would just have to return a ```Task``` (which unfortunately doesn't seem to be that uncommon these days).

Solution 2 would require a huge number of changes the whole way through the project in order to cope with two possible interfaces for command handlers but I'm not going to let that put me off this solution completely.

Solution 3 would work but I would really rather not implement a base class for handlers if it can be avoided.  Plus the way this would need to be implemented could be flakey and open it up for more breakages.

**Comment by JoeStead** [comment]
I think the simplest is solution 1, I imagine async handlers are going to be the norm in most cases.

Solution 2 is probably the cleanest, but then we'd need to differentiate between the two when resolving / running them.

Solution 3 is a whole bunch of nope.

**Comment by jasonmitchell** [comment]
@JoeStead Have a look at the PR and see if that does the trick.
